<?php
/**
 * TL_ROOT/system/modules/import_from_csv/languages/de/modules.php 
 * 
 * Contao extension: import_from_csv 1.0.1 
 * Deutsch translation file 
 * 
 * Copyright :  
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['import_from_csv']['0'] = "CSV Datenbankimport";
 
?>
