<?php
/**
 * TL_ROOT/system/modules/import_from_csv/languages/de/tl_import_from_csv.php 
 * 
 * Contao extension: import_from_csv 1.0.1 
 * Deutsch translation file 
 * 
 * Copyright :  
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_import_from_csv']['manual'] = "Anleitung/Hilfe";
$GLOBALS['TL_LANG']['tl_import_from_csv']['settings'] = "Einstellungen";
$GLOBALS['TL_LANG']['tl_import_from_csv']['import_table']['0'] = "Datentabelle für Import auswählen";
$GLOBALS['TL_LANG']['tl_import_from_csv']['import_table']['1'] = "Wählen Sie eine Tabelle, in welche die Daten importiert werden sollen, aus.";
$GLOBALS['TL_LANG']['tl_import_from_csv']['import_mode']['0'] = "Import-Modus";
$GLOBALS['TL_LANG']['tl_import_from_csv']['import_mode']['1'] = "Entscheiden Sie, ob die Tabelle vor dem Import gelöscht werden soll oder die Daten an die bestehenden Einträge angehängt werden sollen.";
$GLOBALS['TL_LANG']['tl_import_from_csv']['field_enclosure']['0'] = "Felder eingeschlossen von";
$GLOBALS['TL_LANG']['tl_import_from_csv']['field_enclosure']['1'] = "Zeichen, von welchem die Felder in der csv-Datei eingeschlossen sind. Normalerweise ein doppeltes Anführungszeichen: => \"";
$GLOBALS['TL_LANG']['tl_import_from_csv']['field_separator']['0'] = "Felder getrennt von";
$GLOBALS['TL_LANG']['tl_import_from_csv']['field_separator']['1'] = "Zeichen, mit dem die Felder in der csv-Datei voneinander getrennt sind. Normalerweise ein Semikolon: => ;";
$GLOBALS['TL_LANG']['tl_import_from_csv']['selected_fields']['0'] = "Felder für Importvorgang auswählen.";
$GLOBALS['TL_LANG']['tl_import_from_csv']['fileSRC']['0'] = "csv-Datei auswählen";
$GLOBALS['TL_LANG']['tl_import_from_csv']['fileContent']['0'] = "Datei-Inhalt";
$GLOBALS['TL_LANG']['tl_import_from_csv']['truncate_table']['0'] = "Tabelle vor dem Import löschen";
$GLOBALS['TL_LANG']['tl_import_from_csv']['append_entries']['0'] = "Datensätze nur anhängen";
$GLOBALS['TL_LANG']['tl_import_from_csv']['new']['0'] = "Neuen Importdatensatz anlegen";
$GLOBALS['TL_LANG']['tl_import_from_csv']['new']['1'] = "Einen neuen Importdatensatz anlegen";
$GLOBALS['TL_LANG']['tl_import_from_csv']['launchImportButton'] = "Importvorgang starten";
$GLOBALS['TL_LANG']['tl_import_from_csv']['testRunImportButton'] = "Importvorgang im Testmodus starten";
$GLOBALS['TL_LANG']['tl_import_from_csv']['datarecords'] = "Anzahl Datensätze";
$GLOBALS['TL_LANG']['tl_import_from_csv']['successful_inserts'] = "Erfolgreiche inserts";
$GLOBALS['TL_LANG']['tl_import_from_csv']['failed_inserts'] = "Missglückte inserts";
 
?>
