services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  _instanceof:
    Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
      calls:
        - [ setContainer, [ '@service_container' ] ]

  Markocupic\ImportFromCsvBundle\:
    resource: ../src/
    exclude:
      - ../src/{DependencyInjection,Event,Session}
      - ../src/Import/ImportConfig.php

  # Register session bags
  markocupic.import_from_csv.session.factory:
    class: Markocupic\ImportFromCsvBundle\Session\SessionFactory
    decorates: session.factory
    arguments:
      - '@markocupic.import_from_csv.session.factory.inner'
      - '@markocupic.import_from_csv.session.attribute.array_attribute_bag'

  markocupic.import_from_csv.session.attribute.array_attribute_bag:
    class: Markocupic\ImportFromCsvBundle\Session\Attribute\ArrayAttributeBag
    arguments:
      - '_markocupic_import_from_csv_attributes'
    calls:
      - [ 'setName', [ 'markocupic_import_from_csv' ] ]
